package model

type Abiturient struct {
	FirstName                    string  `json:"first_name",xml:"first_name"`
	SecondName                   string  `json:"second_name",xml:"second_name"`
	ThirdName                    string  `json:"third_name",xml:"third_name"`
	LatinFirstName               string  `json:"latin_first_name",xml:"latin_first_name"`
	LatinSecondName              string  `json:"latin_second_name",xml:"latin_second_name"`
	Gender                       string  `json:"gender",xml:"gender",xml:"gender"`
	DateOfBirth                  int   `json:"date_of_birth",xml:"date_of_birth",xml:"date_of_birth"`
	IsForeigner                  bool    `json:"is_foreigner",xml:"is_foreigner",xml:"is_foreigner"`
	Nationality                  string  `json:"nationality",xml:"nationality",xml:"nationality"`
	FamilyStatus                 string  `json:"family_status",xml:"family_status",xml:"family_status"`
	Region                       string  `json:"region"xml:"region"`
	PostIndex                    string  `json:"post_index",xml:"post_index"`
	BirthPlace                   string  `json:"birth_place",xml:"birth_place"`
	RegisterAddress              string  `json:"register_address",xml:"register_address"`
	HomeAddress                  string  `json:"home_address",xml:"home_address"`
	LiveAddress                  string  `json:"live_address",xml:"live_address"`
	PhoneNumber                  string  `json:"phone_number",xml:"phone_number"`
	HomePhoneNumber              string  `json:"home_phone_number",xml:"home_phone_number"`
	DocumentType                 string  `json:"document_type",xml:"document_type"`
	SerialAndPassportNumber      string  `json:"serial_and_passport_number",xml:"serial_and_passport_number"`
	IssuedBy                     string  `json:"issued_by",xml:"issued_by"`
	WhenIssud                    int64   `json:"when_issud",xml:"when_issud"`
	ValidUntil                   int64   `json:"valid_until",xml:"valid_until"`
	PersonalNomer                string  `json:"personal_nomer",xml:"personal_nomer"`
	FormStuding                  string  `json:"form_studing",xml:"form_studing"`
	Faculty                      string  `json:"faculty",xml:"faculty"`
	Specialization               string  `json:"specialization",xml:"specialization"`
	TypeEducation                string  `json:"type_education",xml:"type_education"`
	EducationalInstitution       string  `json:"educational_institution",xml:"educational_institution"`
	EducationSpecialization      string  `json:"education_specialization",xml:"education_specialization"`
	GraduatedInstitutionYear     int64   `json:"graduated_institution_year",xml:"graduated_institution_year"`
	Subject1_Name                string  `json:"subject_1_name",xml:"subject_1_name"`
	Subject2_Name                string  `json:"subject_2_name",xml:"subject_2_name"`
	Subject3_Name                string  `json:"subject_3_name",xml:"subject_3_name"`
	Subject1_Rating              float64   `json:"subject_1_rating",xml:"subject_1_rating"`
	Subject2_Rating              float64   `json:"subject_2_rating",xml:"subject_2_rating"`
	Subject3_Rating              float64   `json:"subject_3_rating",xml:"subject_3_rating"`
	Subject1_Setificate          string  `json:"subject_1_setificate",xml:"subject_1_setificate"`
	Subject2_Setificate          string  `json:"subject_2_setificate",xml:"subject_2_setificate"`
	Subject3_Setificate          string  `json:"subject_3_setificate",xml:"subject_3_setificate"`
	ForigenLangName              string  `json:"forigen_lang_name",xml:"forigen_lang_name"`
	ForigenLangRating            float64   `json:"forigen_lang_rating",xml:"forigen_lang_rating"`
	DocumentTypeEducation        string  `json:"document_type_education",xml:"document_type_education"`
	IsSelskayaShkola             bool    `json:"is_selskaya_shkola",xml:"is_selskaya_shkola"`
	IsGorodskaya                 bool    `json:"is_gorodskaya",xml:"is_gorodskaya"`
	A2019                        bool    `json:"a2019",xml:"a_2019"`
	Medal                        bool    `json:"medal",xml:"medal"`
	Ssuz                         bool    `json:"ssuz",xml:"ssuz"`
	Ptu                          bool    `json:"ptu",xml:"ptu"`
	DocumentEducationNumberNomer string  `json:"document_education_number_nomer",xml:"document_education_number_nomer"`
	DocumentEducationAt          int64   `json:"document_education_at",xml:"document_education_at"`
	AverageMark                  float64 `json:"average_mark",xml:"average_mark"`
	SumMarks                     float64 `json:"sum_marks",xml:"sum_marks"`
	Olimp                        bool    `json:"olimp",xml:"olimp"`
	SpecFondRb                   bool    `json:"spec_fond_rb",xml:"spec_fond_rb"`
	OlimpSport                   bool    `json:"olimp_sport",xml:"olimp_sport"`
	PerviyRazrad                 bool    `json:"perviy_razrad",xml:"perviy_razrad"`
	LgotniyKredit                bool    `json:"lgotniy_kredit",xml:"lgotniy_kredit"`
	Hostel                       bool    `json:"hostel",xml:"hostel"`
	Disabled                     bool    `json:"disabled",xml:"disabled"`
	Chernobil                    bool    `json:"chernobil",xml:"chernobil"`
	AdditionalInformation        string  `json:"additional_information",xml:"additional_information"`
	Email                        string  `json:"email",xml:"email"`
	Privileges                   bool    `json:"privileges",xml:"privileges"`
	InfoPrivileges               string  `json:"info_privileges",xml:"info_privileges"`
	HasFather                    bool    `json:"has_father",xml:"has_father"`
	SecondNameFather             string  `json:"second_name_father",xml:"second_name_father"`
	ThirdNameFather              string  `json:"third_name_father",xml:"third_name_father"`
	AdressFather                 string  `json:"adress_father",xml:"adress_father"`
	WorkAdressFather             string  `json:"work_adress_father",xml:"work_adress_father"`
	ContactFather                string  `json:"contact_father",xml:"contact_father"`
	HasMother                    bool    `json:"has_mother",xml:"has_mother"`
	SecondMotherName             string  `json:"second_mother_name",xml:"second_mother_name"`
	MotherFirstName              string  `json:"mother_first_name",xml:"mother_first_name"`
	ThirdMotherName              string  `json:"third_mother_name",xml:"third_mother_name"`
	WorkMotherAddress            string  `json:"work_mother_address",xml:"work_mother_address"`
	MotherContactInfo            string  `json:"mother_contact_info",xml:"mother_contact_info"`
	OwnerPassport                string  `json:"owner_passport",xml:"owner_passport"`
	OwnerPassportNumber          string  `json:"owner_passport_number",xml:"owner_passport_number"`
	OwnerPassportID              string  `json:"owner_passport_id",xml:"owner_passport_id"`
	OwnerPassportKtoVidal        string  `json:"owner_passport_kto_vidal",xml:"owner_passport_kto_vidal"`
	OwnerPassportKogdaVidal      int64   `json:"owner_passport_kogda_vidal",xml:"owner_passport_kogda_vidal"`
	OwnerPassportSrok            int64   `json:"owner_passport_srok",xml:"owner_passport_srok"`
	PasportPhoto                 string  `json:"pasport_photo",xml:"pasport_photo"`
	CT1_Photo                    string  `json:"ct_1_photo",xml:"ct_1_photo"`
	CT2_Photo                    string  `json:"ct_2_photo",xml:"ct_2_photo"`
	CT3_Photo                    string  `json:"ct_3_photo",xml:"ct_3_photo"`
	CT4_Photo                    string  `json:"ct_4_photo",xml:"ct_4_photo"`
	OwnerPasportPhoto            string  `json:"owner_pasport_photo",xml:"owner_pasport_photo"`
	EducationDocumentPhoto       string  `json:"education_document_photo",xml:"education_document_photo"`
	FirstNameFather string `json:"first_name_father",xml:"first_name_father"`
	AdressMother string `json:"adress_mother",xml:"adress_mother"`
	UniverLocation string `json:"univer_location",xml:"univer_location"`
}